### ISSUE TITLE
Initial state

### ISSUE THREAD

**Issue by nunofgs** [kyleaa/homebridge-samsungtv2016#1]
Hi there!

Just tested this on my KS8000 and it works great! One issue I have is that the initial state is not being retrieved at the moment.

Can we find a way to connect to the TV and determine if it is on of off, when homebridge starts?

**Comment by kyleaa** [comment]
There's an endpoint at `:8001/api/v2/` that returns info about the TV - we could probably try connecting to that, and if it times out then assume the TV is off.

**Comment by kyleaa** [comment]
@nunofgs give this version a try. There's a slight delay with the power on command now (it first hits the API to see if the TV is alive), but it prevents an even longer delay that was present before (how long you had to wait after turning off to turn back on). This is because the TV takes ~ 10 seconds to shut down, so the WOL packet was ignored during this time.

**Comment by craigdent** [comment]
Would this work on the Samsung model - UA55F8000AMXYY
Version - TH01

With the latest evolution kit which EVO2000?

**Comment by nunofgs** [comment]
Working great for me! Takes a few seconds for the on/off status to update, but it's very usable.

Also, mine is connected through wi-fi and I can turn it on and off just fine. I haven't tested letting it sleep for a long time and then turning it on. I'll let you know how that goes.

Thanks for this! Feel free to close this issue.

**Comment by craigdent** [comment]
Does that mean it should work for my model TV?
