### ISSUE TITLE
Functions available for the TV

### ISSUE THREAD

**Issue by abko** [kyleaa/homebridge-samsungtv2016#19]
@kyleaa Thanks for creating a plugin for the SamsungTV. Am I correct that it only supports power on and power off at the moment?
 
Note that I have it running on a Raspberry Pi Zero W. Wake on Lan seems to work over WiFi as well since I can switch my TV On and Off.

I am hoping to be able to do input selection and other features as well (e.g. it would be great to select Netflex on the TV via Homekit ;-) )

Note I am using it with the UE55KS8000, if I am not mistaken equivalent to the UN55KS9000 in the USA.

**Comment by kyleaa** [comment]
That is correct. It should be possible to send any key command that the TV supports (but the protocol is not documented so there's a lot of trial and error). I think the biggest problem with this is that Homekit doesn't appear to have device types/characteristics that would correlate to those actions (eg input switching). You could get around this by doing setting up inputs as different devices (eg, "turn on HDMI 1"), but that would certainly be a hack.

I've switched to using RS-232 protocols over the exlink port as I found it to be more reliable than the API, but I'm also now using alexa instead of homekit 😛

**Comment by abko** [comment]
@kyleaa I am slowly starting to read into Node.js since I am completely new to it. One of the idea's I have is to add a switch that toggles between a to be configured HMDI input and activation of the SmartHub. I realise it's a bit weird, but in generic I either use my AV receiver connected to HDMI4 which is connected to other devices, or I use one of the Samsung Apps, like Netflix, Youtube etc.

I tried to understand how the plugin send the On/Off command to the TV, but don't really understand where KEY_POWER originates from and how I could find an equivalent (if it exists) for sending a command to select for example HDMI1 or to send the commend to call for the SmartHub menu.

I assumed some sort of url was send to the TV to trigger commands, but still don't understand the logic ..

Sorry for these novice questions, but if you have any hints that would be great!

Abko

**Comment by kyleaa** [comment]
As far as supported commands, its sort of a matter of trial and error. Since the older protocol has been reverse-engineered, I tried commands out of https://github.com/natalan/samsung-remote - but not all of them might be implemented on your model.

These models of TV don't use a REST API - they open a websocket connection and send commands over that connection. https://www.html5rocks.com/en/tutorials/websockets/basics/

I had issues with detecting the state of the socket and reconnecting, so I changed my code to open a new socket connection for each remote key transmission. This happens in https://github.com/kyleaa/homebridge-samsungtv2016/blob/master/index.js#L40 - The socket is opened on line 41 - the TV sends back a confirmation message when the connection is successful. Line 48 is listening for that message, and if it is the correct message ("ms.channel.connect"), then it transmits the remote key JSON payload in line 53 and disconnects in line 54.

**Comment by abko** [comment]
Thanks. I think I high level get it :-) I'll do some studying and maybe try a bit in a local copy. Could I just add accessory.sendKey('KEY_HDMI1', ... (including all other code) after a successful https://github.com/kyleaa/homebridge-samsungtv2016/blob/master/index.js#L149 to see if the TV responds to that key? So it would not just switch on the TV, but also select HDMI1?

**Comment by kyleaa** [comment]
That sounds like a plausible approach 🙂. You may need to put in a delay as well

**Comment by josemjorge** [comment]
Hi @kyleaa, do you feel we can make some progress on the other keys functionality based on the latest information from Samsung (http://developer.samsung.com/tv/develop/guides/user-interaction/remote-controller)? This API is supported on 2016 Samsung TV models onwards.
Thanks!

**Comment by kyleaa** [comment]
@zemiguelll The linked documentation is for writing an app that runs on the TV, which is the opposite of what we are doing. As per the previous responses, the blocker on this is HomeKit characteristics, not TV control capability. While you can hack siri into controlling something by abusing characteristics, that's not the goal of this project - but you can certainly copy/manipulate the code to accomplish it.
